# Generated by Django 5.1.3 on 2024-11-15 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0002_day_purchases'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Day',
            new_name='Days',
        ),
    ]
